### ISSUE TITLE
bug when adding node

### ISSUE THREAD

**Issue by mewi** [totetmatt/GephiStreamer#4]
When I run the sample script I get the following error:

Traceback (most recent call last):
  File "test2.py", line 21, in <module>
    stream.add_node(node_a,node_b)
  File "/usr/local/lib/python2.7/site-packages/gephistreamer/streamer.py", line 71, in **call**
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/gephistreamer/streamer.py", line 83, in commit
    self.stream_method.send(self.action())
  File "/usr/local/lib/python2.7/site-packages/gephistreamer/streamer.py", line 80, in action
    return {self.header.value:action_json}
AttributeError: 'str' object has no attribute 'value'

Any idea how to fix this ?

**Comment by totetmatt** [comment]
Issue was due to missing dependency for Python 2.7 version.
It should be fixed now by updating the Library (pip install -U GephiStreamer)
